language: node_js
node_js: "8"
before_install:
    - export TZ=Europe/Oslo
script:
    - "npm run lint"
    - "npm run test:coverage"
    - "npm run heroku-postbuild"
    - "npm-run-all -p -r start test:browserstack"
