language: node_js
node_js: "8"
cache: npm
before_install:
    - export TZ=Europe/Oslo

matrix:
    include:
    - name: test
      script:
      - npm run test

    - name: browserstack
      script:
      - npm run heroku-postbuild
      - npm-run-all -p -r start:test-server test:browserstack
