apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: aktivitetsplan-fss
  namespace: {{namespace}}
  cluster: prod-fss
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/aktivitetsplan/aktivitetsplan:{{version}}
  port: 8080
  liveness:
    path: aktivitetsplan/internal/isAlive
    initialDelay: 20
  readiness:
    path: aktivitetsplan/internal/selftest
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: aktivitetsplan/internal/metrics
  ingresses:
    - https://aktivitetsplan-{{namespace}}.nais.preprod.local
    - https://app-{{namespace}}.adeo.no/aktivitetsplan
  vault:
    enabled: true
  webproxy: true
  env:
    - ISSO_JWKS_URL
    - ISSO_HOST_URL
    - ISSO_ISSUER_URL
    - ISSO_ISALIVE_URL
    - VEILARBLOGIN_REDIRECT_URL_URL
    - VEILARBLOGIN_REDIRECT_URL_DESCRIPTION
    - OIDC_REDIRECT_URL
    - AAD_B2C_DISCOVERY_URL
    - UNLEASH_API_URL
    - name: VEIENTILARBEID_URL
      value: 'https://veientilarbeid-q.nav.no'
    - name: DITTNAV_LINK_URL
      value: 'https://tjenester-{{namespace}}.nav.no/dittnav/'
    - name: AKTIVITETSPLAN_URL
      value: 'https://aktivitetsplan-q.nav.no'
    - name: ARBEIDSSOKERREGISTRERING_URL
      value: 'https://arbeidssokerregistrering-q.nav.no/'
    - name: REGISTRERINGSINFORMASJON_URL
      value: 'https://registreringsinformasjon-q.nav.no'
    - name: VEILARBSTEPUP_OIDC_URL
      value: 'https://veilarbstepup-q.nav.no/veilarbstepup/oidc'
    - name: DISABLE_PROXY
      value: 'true'
    - name: DISABLE_DECORATOR
      value: 'true'
    - name: CONFIGURATION_LOCATION
      value: '/decorator-fss.yaml'
