apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: aktivitetsplan-intern
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/pto-frontend/pto-frontend:2021.11.22_08.26-db566af030c4
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  ingresses:
    - https://aktivitetsplan.dev.intern.nav.no
  accessPolicy:
    outbound:
      rules:
        - application: pto-proxy
      external:
        - host: navtestb2c.b2clogin.com
  gcp:
    buckets:
      - name: aktivitetsplan-dev-intern
  envFrom:
    - configmap: pto-config
  env:
    - name: ENFORCE_LOGIN
      value: "false"
    - name: GCS_BUCKET_NAME
      value: aktivitetsplan-dev-intern
    - name: PUBLIC_STILLING_FRA_NAV_BASE_URL
      value: 'https://rekrutteringsbistand.nais.preprod.local/stillinger/stilling/'
    - name: CORS_DOMAIN
      value: "*"
