apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: aktivitetsplan
  namespace: pto
  labels:
    team: pto
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: aktivitetsplan/internal/isAlive
    initialDelay: 20
  readiness:
    path: aktivitetsplan/internal/selftest
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: aktivitetsplan/internal/metrics
  ingresses:
    - https://aktivitetsplan-q1.nav.no
    - https://aktivitetsplan-q1.dev.nav.no
    - https://aktivitetsplan.dev.nav.no

  vault:
    enabled: true
  webproxy: true
  env:
    - name: APP_ENVIRONMENT_NAME
      value: q1
    - name: DITTNAV_LINK_URL
      value: 'https://tjenester-q1.nav.no/dittnav/'
    - name: PUBLIC_STILLING_FRA_NAV_BASE_URL
      value: 'https://vis-stilling.dev.nav.no/arbeid/stilling/'
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
