apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: aktivitetsplan
  namespace: {{namespace}}
  cluster:
    - dev-fss
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/aktivitetsplan/aktivitetsplan:{{version}}
  port: 8080
  liveness:
    path: aktivitetsplan/internal/isAlive
    initialDelay: 60
  readiness:
    path: aktivitetsplan/internal/selftest
    initialDelay: 60
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: aktivitetsplan/internal/metrics
  ingresses:
    - https://aktivitetsplan-{{namespace}}.nais.preprod.local
    - https://app-{{namespace}}.adeo.no/aktivitetsplan
  env:
    - ISSO_JWKS_URL
    - ISSO_HOST_URL
    - ISSO_ISSUER_URL
    - ISSO_ISALIVE_URL
    - VEILARBLOGIN_REDIRECT_URL_URL
    - VEILARBLOGIN_REDIRECT_URL_DESCRIPTION
    - OIDC_REDIRECT_URL
    - UNLEASH_API_URL
    - name: VEILARBSTEPUP_OIDC_URL
      value: "https://veilarbstepup-q.nav.no/veilarbstepup/oidc"
    - name: DISABLE_PROXY
      value: "true"
    - name: DISABLE_DECORATOR
      value: "true"
