apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: aktivitetsplan
  namespace: default
  cluster: prod-sbs
  labels:
    team: pto
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: aktivitetsplan/internal/isAlive
    initialDelay: 60
  readiness:
    path: aktivitetsplan/internal/selftest
    initialDelay: 60
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: aktivitetsplan/internal/metrics
  ingresses:
    - https://aktivitetsplan.nav.no
    - https://tjenester.nav.no/aktivitetsplan
  vault:
    enabled: true
  webproxy: true
  env:
    - name: DITTNAV_LINK_URL
      value: 'https://tjenester.nav.no/dittnav/'
  envFrom:
    - configmap: pto-config
