apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: aktivitetsplan-fss
  namespace: pto
  labels:
    team: pto
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: aktivitetsplan/internal/isAlive
    initialDelay: 20
  readiness:
    path: aktivitetsplan/internal/selftest
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: aktivitetsplan/internal/metrics
  ingresses:
    - https://aktivitetsplan-q1.nais.preprod.local
    - https://app-q1.adeo.no/aktivitetsplan
    - https://app-q1.dev.adeo.no/aktivitetsplan
  vault:
    enabled: true
  webproxy: true
  env:
    - name: DISABLE_PROXY
      value: 'true'
    - name: DISABLE_DECORATOR
      value: 'true'
    - name: CONFIGURATION_LOCATION
      value: '/decorator-fss.yaml'
    - name: PUBLIC_STILLING_FRA_NAV_BASE_URL
      value: 'https://rekrutteringsbistand.nais.preprod.local/stillinger/stilling/'
  envFrom:
    - configmap: pto-config
