version: 2.1
jobs:
    loadsay:
        machine: true
        steps:
            - run: echo "hi"

    sayhello: &sayhello_ref
        machine: true
        steps:
            - run: echo "hello"

    SayHelloChad:
        <<: *sayhello_ref
        steps:
            - run: echo "blee"

    saygoodbye:
        machine: true
        steps:
            - run: echo "bye"

workflows:
    version: 2
    build:
        jobs:
            - loadsay
            - sayhello:
                  requires:
                      - loadsay

            - SayHelloChad

            - saygoodbye:
                  requires:
                      - SayHelloChad
