# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.15

        steps:
            - checkout
            - run: npm install
            - run: npm run build

    unittest:
        environment:
            TZ: Europe/Oslo

        docker:
            - image: circleci/node:10.15

        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
            - run: npm install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run: npm run test

    browsertest:
        docker:
            - image: circleci/node:10.15

        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
            - run: npm install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run: npm run build:tekster
            - run: npm run test:browsers

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - unittest
            - browsertest
