version: 2.1
orbs:
    pus: navikt/pus-orb@0.0.22

workflows:
    version: 2
    commit:
        jobs:
            - pus/test-frontend:
                  - name: test

            - pus/bygg_frontend:
                  requires:
                      - test
                  name: build
                  context: pus
                  cluster: dev-fss
                  filters:
                      branches:
                          only: master

            - pus/deploy-latest:
                  requires:
                      - build
                  name: deploy1
                  context: pus
                  cluster: dev-sbs
                  filters:
                      branches:
                          only: master

            - pus/deploy-latest:
                  requires:
                      - build
                  name: deploy2
                  context: pus
                  cluster: dev-fss
                  filters:
                      branches:
                          only: master
            - prodsett:
                  requires:
                      - deploy1
                      - deploy2
                  type: approval
                  filters:
                      branches:
                          only: master

            - pus/deploy-latest:
                  requires:
                      - prodsett
                  context: pus
                  cluster: prod-fss
                  filepath: ./nais.yaml
                  filters:
                      branches:
                          only: master

            - pus/deploy-latest:
                  requires:
                      - prodsett
                  context: pus
                  cluster: prod-sbs
                  filepath: ./nais.yaml
                  filters:
                      branches:
                          only: master

