version: 2.1
orbs:
    pus: navikt/pus-orb@0.0.20

jobs:
    - bygg_og_deploy_fss:
          <<: *pus/bygg-og-deploy-frontend-ref
          cluster: dev-fss


workflows:
    version: 2
    commit:
        jobs:
            - pus/test-frontend:
                  context: pus
                  filters:
                      branches:
                          ignore: master
            - bygg_og_deploy_fss:
                  context: pus
                  filters:
                      branches:
                          only: master
            - prodsett:
                  requires:
                      - pus/deploy-frontend
                  type: approval
                  filters:
                      branches:
                          only: master
            - pus/deploy-latest:
                  requires:
                      - prodsett
                  context: pus
                  cluster: prod-fss
                  filepath: ./nais.yaml
                  filters:
                      branches:
                          only: master
