apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: aktivitetsplan
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2022.12.12_15.14-6d2623ef615d
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
  tokenx:
    enabled:
      true
  ingresses:
    - https://aktivitetsplan.nav.no
  resources:
    limits:
      cpu: "3"
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 512Mi
  accessPolicy:
    outbound:
      rules:
        - application: pto-proxy
      external:
        - host: navnob2c.b2clogin.com
  gcp:
    buckets:
      - name: aktivitetsplan-prod
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
  env:
    - name: JSON_CONFIG
      value: >
        {
          "gcs": {
            "bucketName": "aktivitetsplan-prod"
          },
          "auth": {
            "loginProvider": "ID_PORTEN"
          },
          "header": {
            "csp": {
              "default-src":["*.nav.no"],
              "script-src":["*.nav.no","*.psplugin.com","*.hotjar.com","*.taskanalytics.com","'unsafe-inline'","'unsafe-eval'"],
              "script-src-elem":["*.nav.no","*.psplugin.com","*.hotjar.com","*.taskanalytics.com","'unsafe-inline'"],
              "worker-src":["blob:"],"child-src":["blob:"],"style-src":["*.nav.no","*.psplugin.com","'unsafe-inline'"],
              "style-src-elem":["*.nav.no","*.psplugin.com","'unsafe-inline'"],
              "font-src":["*.psplugin.com","*.hotjar.com","cdn.nav.no","data:"],
              "img-src":["*.nav.no","*.psplugin.com","*.vimeocdn.com","*.hotjar.com","www.vergic.com"],
              "frame-src":["*.hotjar.com","player.vimeo.com","video.qbrick.com"],
              "connect-src":["*.nav.no","*.boost.ai","*.psplugin.com","*.hotjar.com","*.hotjar.io","*.taskanalytics.com"]
            }
          },
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "proxies": [
            { "fromPath": "/veilarbvedtakinfo", "toUrl": "http://pto-proxy/proxy", "preserveFromPath": true, "toApp": {"name": "veilarbvedtakinfo", "namespace": "pto", "cluster": "prod-fss" } },
            { "fromPath": "/veilarblest", "toUrl": "http://pto-proxy/proxy", "preserveFromPath": true, "toApp": {"name": "veilarblest", "namespace": "pto", "cluster": "prod-fss" } },
            { "fromPath": "/veilarboppfolging", "toUrl": "http://pto-proxy/proxy", "preserveFromPath": true, "toApp": {"name": "veilarboppfolging", "namespace": "pto", "cluster": "prod-fss" } },
            { "fromPath": "/veilarbdialog", "toUrl": "http://pto-proxy/proxy", "preserveFromPath": true, "toApp": {"name": "veilarbdialog", "namespace": "pto", "cluster": "prod-fss" } },
            { "fromPath": "/veilarbaktivitet", "toUrl": "http://pto-proxy/proxy", "preserveFromPath": true, "toApp": {"name": "veilarbaktivitet", "namespace": "pto", "cluster": "prod-fss" } }
          ],
          "redirects": [
            {
              "fromPath": "/api/auth",
              "toUrl": "/auth/info"
            },
            {
              "fromPath": "/aktivitetsplan",
              "toUrl": "{{AKTIVITETSPLAN_URL}}"
            },
            {
              "fromPath": "/arbeidssokerregistrering",
              "toUrl": "{{ARBEIDSSOKERREGISTRERING_URL}}"
            },
            {
              "fromPath": "/minside",
              "toUrl": "{{MINSIDE_URL}}"
            },
            {
              "fromPath": "/veientilarbeid",
              "toUrl": "{{VEIENTILARBEID_URL}}"
            },
            {
              "fromPath": "/arbeidsrettet-dialog",
              "toUrl": "{{ARBEIDSRETTET_DIALOG_URL}}",
              "preserveFromPath": "true"
            },
            {
              "fromPath": "/dialog",
              "toUrl": "{{ARBEIDSRETTET_DIALOG_URL}}",
              "preserveFromPath": "true"
            }
          ]
        }
