name: deploy dev og prod
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  dev-ekstern:
    name: Deploy to dev extern
    uses: navikt/aktivitetsplan/.github/workflows/gcp-root.yml@main
    with:
      kommando: npm run build:dev-ekstern
      bucket: aktivitetsplan-dev
      releaseName: dev-ekstern
    secrets:
      GCS_SA_KEY: ${{ secrets.GCS_SA_KEY_DEV }}

  dev-intern:
    name: Deploy application to dev intern
    uses: navikt/aktivitetsplan/.github/workflows/gcp-root.yml@main
    with:
      kommando: npm run build:dev-intern
      bucket: aktivitetsplan-dev-intern
      releaseName: dev-intern
    secrets:
      GCS_SA_KEY: ${{ secrets.GCS_SA_KEY_DEV }}

  prod-ekstern:
    name: Deploy application to prod ekstern
    needs: dev-ekstern
    uses: navikt/aktivitetsplan/.github/workflows/gcp-root.yml@main
    with:
      kommando: npm run build:prod-ekstern
      bucket: aktivitetsplan-prod
      releaseName: prod-ekstern
    secrets:
      GCS_SA_KEY: ${{ secrets.GCS_SA_KEY_PROD }}

  prod-ekstern-sentry-release:
    needs: prod-ekstern
    name: Upload sourcemaps to sentry (ekstern)
    uses: getsentry/action-release@v1
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: nav
      SENTRY_PROJECT: aktivitetsplan
      SENTRY_URL: https://sentry.gc.nav.no/
    with:
      environment: prod
      sourcemaps: './build'

  prod-intern:
    name: Deploy application to prod intern
    needs: dev-intern
    uses: navikt/aktivitetsplan/.github/workflows/gcp-root.yml@main
    with:
      kommando: npm run build:prod-intern
      bucket: aktivitetsplan-prod-intern
      releaseName: prod-intern
    secrets:
      GCS_SA_KEY: ${{ secrets.GCS_SA_KEY_PROD }}
