name: GCP dev

on:
  workflow_call:
    inputs:
      kommando:
        required: true
        type: string
      bucket:
        required: true
        type: string
      releseName:
        required: true
        type: string
    secrets:
      GCS_SA_KEY:
        required: true

jobs:
  deploy-dev:
    name: Deploy application to dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Build application
        run: ${{ inputs.kommando }}
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCS_SA_KEY }}
          export_default_credentials: true
      - name: Upload files to GCS
        run: gsutil -m rsync -r build "$BUKET"
        env:
          BUKET: gs://${{ inputs.bucket }}
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release/dev/${{inputs.releseName}}@${{ github.sha }}
          release_name: ${{ inputs.releseName }}
          prerelease: true
