name: GCP dev

on:
  workflow_call:
    inputs:
      kommando:
        required: true
        type: string
      bucket:
        required: true
        type: string
      releseName:
        required: true
        type: string


  push:
    paths-ignore:
      - '.github/workflows/pto-frontend-container.yml'
      - 'nais-q-gcp.yaml'
      - 'nais-q-intern-gcp.yaml'
  workflow_dispatch:

concurrency:
  group: gcp_dev
  cancel-in-progress: true

jobs:
  deploy-dev:
    name: Deploy application to dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Build application
        run: ${{ inputs.kommando }}
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCS_SA_KEY_DEV }}
          export_default_credentials: true
      - name: Upload files to GCS
        run: gsutil -m rsync -r build "gs://${{ inputs.bucket }}"
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release/dev@${{ github.sha }}
          release_name: ${{ inputs.releseName }}
          prerelease: true
