name: GCP dev

on:
  push:
    paths-ignore:
      - '.github/workflows/pto-frontend-container.yml'
      - 'nais-q-gcp.yaml'
      - 'nais-q-intern-gcp.yaml'
  workflow_dispatch:

concurrency:
  group: gcp_dev
  cancel-in-progress: true

jobs:
  deploy-dev:
    name: Deploy application to dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: ./.github/workflows/gcp-root.yml
        with:
          kommando: npm run build-ekstern-dev
          bucket: aktivitetsplan-dev
          releseName: dev-ekstern
